### ISSUE TITLE
uart_ready() Error

### ISSUE THREAD

**Issue by TurtleForGaming** [compujuckel/nspire-io#6]
So I wrote this script:

```
#include <os.h>
#include <nspireio/uart.hpp>
#include <nspireio/console.hpp>

int key_already_pressed = 0;
char oldinput[100] = {0};
char voidlist[100] = {0};
int dispInput = 0;

int main(void)
{
	assert_ndless_rev(874);
	//clrscr();
	nio_console csl;
	nio_init(&csl,NIO_MAX_COLS,NIO_MAX_ROWS,0,0,NIO_COLOR_WHITE,NIO_COLOR_BLACK,TRUE);
	nio_set_default(&csl);
	nio_color(&csl,NIO_COLOR_BLACK,NIO_COLOR_WHITE);
	nio_printf("Nspire UART Chat by Samy. Compiled the %s At %s\n",__DATE__,__TIME__);
	nio_color(&csl,NIO_COLOR_WHITE,NIO_COLOR_BLACK);
	nio_puts("Press any ESC to exit and CTRL to send msg...\n");
	while(!isKeyPressed(KEY_NSPIRE_ESC)){
		if(isKeyPressed(KEY_NSPIRE_CTRL) && !key_already_pressed){
			nio_printf(">");
			char input2[100] = {0};
			nio_getsn(input2,100);
			uart_printf("\r\n");
			uart_printf(input2);
			key_already_pressed = 1;
		}
		if(!any_key_pressed())
			key_already_pressed = 0;
		if(uart_ready()) {
			char input[100] = {0};
			uart_getsn(input,100);
			if(strcmp(oldinput,input) != 0) {
				if(input != voidlist) {
					nio_puts(input);
					strcpy(oldinput,input);
					strcpy(input,voidlist);
				}
			}
		}
	}
	nio_puts("Tests finished.");
	nio_free(&csl);   
	return 0;
} 
```
 
But It keep writting the the buffer (input) on the serial console (arduino) **AND** the TI Nspire
After searching It's apparently the uart_ready() function that give always true return after one message. Is there a way to clear the serial buffer of the Ti orsomething like this ?

**Comment by compujuckel** [comment]
Are you using an Nspire CX?

**Comment by TurtleForGaming** [comment]
An CX CAS

**Comment by compujuckel** [comment]
Alright, the UART code for the CX has never been tested on real hardware since I only own an Nspire Classic. The current implementation of uart_ready might be wrong: https://github.com/compujuckel/nspire-io/blob/master/arch-nspire/nspire-uart.c#L31

Documentation for the CX UART is here: http://infocenter.arm.com/help/topic/com.arm.doc.ddi0183f/DDI0183.pdf
Currently we are checking bit 1 (DSR) of the UART flag register (page 52), but we should be checking bit 4 (RXFE) or bit 6 (RXFF) instead.
Like I said I don't have hardware to test this on so your best bet is to experiment around with the UART code.

**Comment by TurtleForGaming** [comment]
I can be your tester lol

**Comment by compujuckel** [comment]
I don't have the Ndless SDK set up right now so I can't give much help here.
(You might notice the last commit is 3 years ago ;D)

You can try to change line 34 in the above file to
`return is_classic ? *line_status_reg & 0b1 : !(*line_status_reg & 0b10000);`

**Comment by TurtleForGaming** [comment]
Thank a LOT It's working now
