### ISSUE TITLE
uart_getchar block the program!

### ISSUE THREAD

**Issue by TurtleForGaming** [compujuckel/nspire-io#7]
So this function:
`
char uart_getchar(void)
{
	volatile unsigned *recv_buffer_reg = (unsigned*)0x90020000;
	while(!uart_ready())
		idle();
	char tmp = *recv_buffer_reg;
	uart_putchar(tmp);
	return tmp;
}
`
block's the programm and wait for incomming data is there a solution for just if there is data so execute the rest of the function or not ?

**Comment by compujuckel** [comment]
Yes, getchar is blocking, this is intended.
If you look at the code, you can see that there is a while loop that idles until a character is received.
You could just create your own getchar without this loop.

Since this is not a bug in Nspire I/O and more of a general programming question I would suggest asking such questions in forums like https://tiplanet.org/ or http://codewalr.us/ .
